package ii.dao.mybatis.entity;

import ii.dao.mybatis.MyBatisRoot;

public class UserKey extends MyBatisRoot {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Wed Oct 31 11:12:31 CST 2018
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Wed Oct 31 11:12:31 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Wed Oct 31 11:12:31 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }
}